//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShawnaThai_Eiei.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class history_sell
    {
        public history_sell()
        {
            this.user = new HashSet<user>();
        }
    
        public int Sell_NumID { get; set; }
        public string Sell_Date { get; set; }
        public int ProD_IDSell { get; set; }
        public string AD_ID { get; set; }
    
        public virtual product_rice product_rice { get; set; }
        public virtual ICollection<user> user { get; set; }
    }
}
