//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShawnaThai_Eiei.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shawnathaidpuEntities : DbContext
    {
        public shawnathaidpuEntities()
            : base("name=shawnathaidpuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin_cooperative> admin_cooperative { get; set; }
        public DbSet<cooperative> cooperative { get; set; }
        public DbSet<farmer> farmer { get; set; }
        public DbSet<history_sell> history_sell { get; set; }
        public DbSet<product_rice> product_rice { get; set; }
        public DbSet<ricetype> ricetype { get; set; }
        public DbSet<user> user { get; set; }
    }
}
