//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShawnaThai_Eiei.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ricetype
    {
        public ricetype()
        {
            this.product_rice = new HashSet<product_rice>();
        }
    
        public string RType_Name { get; set; }
        public Nullable<bool> RType_Nape { get; set; }
        public Nullable<bool> RType_Napung { get; set; }
    
        public virtual ICollection<product_rice> product_rice { get; set; }
    }
}
