//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShawnaThai_Eiei.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.history_sell = new HashSet<history_sell>();
        }
    
        public string U_IDCard { get; set; }
        public string U_Password { get; set; }
        public string U_Name { get; set; }
        public string U_Lastname { get; set; }
        public string U_Tel { get; set; }
    
        public virtual ICollection<history_sell> history_sell { get; set; }
    }
}
